# Generated by Django 5.0.6 on 2024-09-11 22:42

import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('start_date', models.DateField(verbose_name='Начало обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание обучения')),
                ('education_level', models.CharField(choices=[('highschool', 'Среднее образование'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Доктор наук')], max_length=50, verbose_name='Уровень образования')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('native', 'Носитель языка')], max_length=50, verbose_name='Уровень владения')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык программирования')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='JobSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='jobs.jobcategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('required_experience', models.IntegerField(verbose_name='Опыт работы (в годах)')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная зарплата')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальная зарплата')),
                ('work_type', models.CharField(choices=[('fulltime', 'Полный рабочий день'), ('parttime', 'Частичная занятость'), ('contract', 'Контракт')], max_length=50, verbose_name='Тип занятости')),
                ('work_format', models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибрид')], max_length=50, verbose_name='Формат работы')),
                ('education_levels', models.ManyToManyField(blank=True, related_name='required_jobs', to='jobs.education', verbose_name='Образование (требуется)')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobsubcategory', verbose_name='Подкатегория')),
                ('languages', models.ManyToManyField(blank=True, related_name='preferred_jobs', to='jobs.language', verbose_name='Языки (предпочтительны)')),
                ('programming_languages', models.ManyToManyField(to='jobs.programminglanguage', verbose_name='Языки программирования')),
                ('skills', models.ManyToManyField(to='jobs.skill', verbose_name='Навыки')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Профиль LinkedIn')),
                ('experience_years', models.IntegerField(verbose_name='Опыт работы (в годах)')),
                ('preferred_city', models.CharField(max_length=100, verbose_name='Предпочитаемый город')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('salary_range_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная зарплата')),
                ('salary_range_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальная зарплата')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[jobs.models.validate_file_size], verbose_name='Резюме (файл)')),
                ('work_type', models.CharField(choices=[('fulltime', 'Полный рабочий день'), ('parttime', 'Частичная занятость'), ('contract', 'Контракт')], max_length=50, verbose_name='Тип занятости')),
                ('work_format', models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибрид')], max_length=50, verbose_name='Формат работы')),
                ('education', models.ManyToManyField(to='jobs.education', verbose_name='Образование')),
                ('languages', models.ManyToManyField(to='jobs.language', verbose_name='Языки')),
                ('programming_languages', models.ManyToManyField(to='jobs.programminglanguage', verbose_name='Языки программирования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('skills', models.ManyToManyField(to='jobs.skill', verbose_name='Навыки')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
