# Generated by Django 5.0.6 on 2024-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_employer_employeroffer_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='moderation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
