# Generated by Django 5.0.6 on 2024-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_moderation_comment_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='programming_languages',
        ),
        migrations.RemoveField(
            model_name='job',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='job',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='resume',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
    ]
