# Generated by Django 5.1.1 on 2024-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Sturtup', 'Стартап'), ('Product', 'Продукт'), ('Outsource', 'Аутсорс'), ('Outstaff', 'Аутстаф')], default='pending', max_length=20, verbose_name='тайпы работы'),
        ),
    ]
