# Generated by Django 5.1.1 on 2024-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='county',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
