# Generated by Django 5.1.1 on 2024-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_county_job_country_job_name_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='best_candidant',
            field=models.CharField(max_length=400, null=True, verbose_name='Идеальный кандидат '),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
