# Generated by Django 5.1.1 on 2024-10-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_best_candidant_job_created_at_resume_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name_company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
    ]
