# Generated by Django 5.1.1 on 2024-10-05 20:12

import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_name_company_remove_job_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sturtup', 'Стартап'), ('Product', 'Продукт'), ('Outsource', 'Аутсорс'), ('Outstaff', 'Аутстаф')], max_length=50, verbose_name='Тип компании')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибрид')], max_length=50, verbose_name='Формат работы')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fulltime', 'Полный рабочий день'), ('parttime', 'Частичная занятость'), ('contract', 'Контракт')], max_length=50, verbose_name='Тип занятости')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='required_experience',
            field=models.IntegerField(validators=[jobs.validators.validate_positive_exp], verbose_name='Опыт работы (в годах)'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_format',
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_type',
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ManyToManyField(to='jobs.companytype', verbose_name='Тип компании'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_format',
            field=models.ManyToManyField(to='jobs.workformat', verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.ManyToManyField(to='jobs.worktype', verbose_name='Тип занятости'),
        ),
    ]
