# Generated by Django 5.1.1 on 2024-09-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialauth', '0005_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
