# Generated by Django 5.1.1 on 2024-09-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialauth', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
